more updates to user permissions

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -48,6 +48,9 @@ services:
       - "4003"  
       - "4004"  
 
+  version: '3'
+name: algo-trader
+services:
   jupyter-quant:
     build:
       context: ./jupyter-quant
@@ -71,6 +74,10 @@ services:
         if [ ! -w /home/quant/Notebooks ]; then
           echo 'Notebooks directory is not writable. Changing permissions...'
           sudo chown -R quant:quant /home/quant/Notebooks
+        fi &&
+        if [ ! -L /home/quant/Notebooks/.lsp_symlink ]; then
+          echo 'Attempting to create .lsp_symlink...'
+          ln -s / /home/quant/Notebooks/.lsp_symlink || echo 'Failed to create .lsp_symlink, but continuing...'
         fi &&
         jupyter lab --ip=0.0.0.0 --no-browser --NotebookApp.token=${JUPYTER_TOKEN:-} --NotebookApp.password= --ContentsManager.allow_hidden=True
       "
